<?php
/**
 * 
 *
 * @author Irlei
 */
$username = '';
if (isset($_POST['username']))
    $username = $_POST['username'];
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link rel="shortcut icon" href="/imagens/missao_icon.png" type="image/x-icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
            <link rel="stylesheet" href="../css/style.css" type="text/css"/>
            <script src="../script/ajax.js" type="text/javascript"></script>
            <script src="../script/jquery.min.js" type="text/javascript"></script>
            <title>Missão Criativa</title>
    </head>
    <body>
        <div id="tudo">
            <div id="topo_menu">
                <div id="cabecalho">
                    <a href="http://www.missaocriativa.com.br">
                        <img  class="missao_logo" src="../imagens/sistem/missao_logo_star.png"/>
                    </a><h1>Missão Criativa</h1>
                    <div  style="margin-right: 100px; margin-top: 50px;">
                    <a class="nav_menu_bar lnk_config" href="../page/novo_usuario.phtml?acao=add">cadastre-se</a>
</div>
                </div><!--cabeçalho menu-->
            </div><!--navegação-->
            <div class="conteudo">
                <div class="login">
                    <form id="form_login" action="../page_controle/login.php" method="POST">
                        <ul>
                            <li>
                                <span class="msg_erro_form"  id="msg_erro_input_login_username"></span>
                            </li><li>
                                <label class="login_label">Usuário:</label> <input  type="text" name="username" id="username" value="<?php echo $username ?>"required="true"/>
                            </li><li>
                                <span class="msg_erro_form"  id="msg_erro_input_login_senha"></span>
                            </li><li>
                                <label  class="login_label">Senha:</label> <input  type="password" name="senha" id="senha" required="true"/>
                            </li>
                            <li>
                                <input  class="button_login"  type="button"  onclick="login();" value="Entrar"/>
                            </li>
                        </ul>

                    </form>

                </div>

            </div>



            <div style="width: 100px; float: left;">
                <?php require_once '../util/mascara.php'; ?>
            </div>
        </div>
        <div id="rodade_pe">
            <?php require_once '../util/rodape.php'; ?>
        </div>
        <?php if (isset($_POST['err'])) {?>
            <script>login_erro();</script>
        <?php unset($_POST['err']);} ?>

        <script src="../script/sha512.js" type="text/javascript"></script>
    </body>
</html>