<?php
/**
 * 
 *
 * @author Irlei
 */
require '../page_controle/is_sessao.php';
require_once '../util/Util.php';
require_once '../model_controle/UsuarioControle.php';
require_once '../model/Usuario.php';
//var_dump($_SESSION);
$acao = isset($_GET['acao']);
$erros = null;
$usuario_controle = new UsuarioControle();
$edicao = false;
$is_admin = false;
$status = UsuarioControle::CLIENTE;
$user_id = 0;
$tipo_op = '';
$info_login = false;

$user = (object) $_SESSION['user'];

if ($acao) {
    $tipo_op = 'Novo';
}


//dados para o formulário
$form = array(
    'id' => 0,
    'nome' => '',
    'sobrenome' => '',
    'dt_nascimento' => '',
    'status' => '',
    'uf' => 0,
    'cidade' => 0,
    'endereco' => '',
    'telefone' => '',
    'img_perfil' => Util::IMAGEM_PADRAO_USUARIO,
    'email' => '',
    'username' => '');

//se for uma edição
if ($acao && isset($_GET['id'])) {
    $edicao = true;
    $tipo_op = "Editar";
}

if ($acao && isset($_SESSION['mlogin'])) {
    $info_login = true;
}

if (isset($_GET['add'])) {
    $tipo_op = 'Detalhes do';
}


$status = $user->status;
//$user_id é o id do usuario logado
$user_id = $user->id;
//se o formulario ja estiver sido submetido e retorna com mensagens de erros para o usuario
if (!empty($_SESSION['msg_erro'])) {
    $erros = $_SESSION['msg_erro'];
    unset($_SESSION['msg_erro']);
}


if ($edicao && $user_id == $edicao || $status == UsuarioControle::ADMIN) {
    $form = $usuario_controle->getArray($_GET['id'], $info_login);
}


if ($status == UsuarioControle::ADMIN) {
    $is_admin = true;
}
//var_dump($form);
unset($usuario_controle);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link rel="shortcut icon" href="/imagens/missao_icon.png" type="image/x-icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></meta>
        <link rel="stylesheet" href="../css/style.css" type="text/css"/>
        <script src="../script/js.js" type="text/javascript"></script>
        <script src="../script/ajax.js" type="text/javascript"></script>
        <script src="../script/jquery.min.js" type="text/javascript"></script>        <title>Missão Criativa</title>
    </head>
    <body>


        <div id="tudo">
            <div id="topo_menu">
                <div id="cabecalho">
                    <a href="http://www.missaocriativa.com.br"> <img  class="missao_logo" src="../imagens/sistem/missao_logo_star.png" ></a>
                    <label class="page_titulo"> <h1 ><?php echo "$tipo_op Usuário" ?></h1></label>
                    <?php if (!$acao) { ?>
                        <a  class="nav_menu_bar lnk_config" href="../page/servico.phtml">anúncios</a>
                        <a  class="nav_menu_bar lnk_config" href="../page/evento.phtml">eventos</a>
                    <?php } elseif ($is_admin) { ?>
                        <a class="nav_menu_bar lnk_config" href="../page/usuario.phtml?acao=add">novo</a>
                        <a  class="nav_menu_bar lnk_config" href="../page/home.phtml">menu</a>
                    <?php } ?>
                    <a  class="nav_menu_bar lnk_config" href="../page/home.phtml">início</a>

                </div><!--cabeçalho-->
            </div><!--menu-->
            <div class="conteudo">
                <?php if (!$acao && !isset($_GET['add'])) { ?>
                    <ul class="menu_home">
                        <?php if ($is_admin) { ?>
                            <a href="usuario.phtml?acao=add"> <li> novo</li></a>
                            <a href="../page/relat_user.php"><li>exibir todos</li></a>
                        <?php } ?>

                    </ul>
                <?php } elseif ($acao) {//Se existe o parametro acao  o formulario será exibido ?>
                    <form id="form" onchange="erroClean();" action="<?php echo Util::crearLink('../page_controle/post_user.php', array('acao' => $_GET['acao'])); ?>" method="post" enctype='multipart/form-data'>
                        <div class="conteudo_form">
                            <?php if ($_GET['acao'] == 'edit' && !$info_login) { ?>
                                <label style="widt:"440px;"><a id="edit_info_login_lnk" href="javascript:editarinfoLogin(<?php echo $form['id'] ?>);">Clique para alterar informações de login.</a></label>
                            <?php } elseif ($form['id'] == $user->id && $info_login) { ?>

                                <div id="info_login">
                                    <h3>Informações para login</h3>
                                    <label>
                                        <output class="msg_erro_input_email msg_erro_form"></output><br>
                                            <span  > Email: <i>*</i></span><input onblur="validarEmail('<?php
                        $email = $form['email'];
                        echo $email . '\',\'' . $user->id
                                ?>') "type="email" class="input_text" id="email" name="email"  value="<?php echo $form['email']; ?>" /></label>

                                    <label>
                                        <output class="msg_erro_input_username"class="msg_erro_form"></output><br>
                                            <span>Nome de Usuário:<i>*</i></span><input class="input_text"  id="username" type="text"  name="username" value="<?php echo $form['username'] ?>"/>
                                    </label>

                                    <div id="box_login_pw">
                                        <label>
                                            <output class="msg_erro_input_senha msg_erro_form"></output><br>
                                                <span>Senha:<i>*</i></span><input onblur="dicaDeSenha(); " class="input_text" id="senha" type="password" placeholder="Mínimo de 6 caracteres"   name="senha" /></label>
                                        <label>
                                            <output class="msg_erro_input_c_senha msg_erro_form"></output><br>
                                                <span> Confirma Senha:<i>*</i></span><input  onblur="validarSenha(); " class="input_text"  type="password" id="c_senha" name="c_senha" /></label>
                                    </div>
                                </div>
                            <?php }if ($is_admin) { ?>
                                <label>
                                    <output class="msg_erro_input_status msg_erro_form"> </output><br>
                                        <span>Status:<i>*</i></span>
                                        <select  id="status" name="status" class="input_text"  title="Escolha o status">
                                            <option class="selec_tipo"  value="0">----</option>
                                            <?php
                                            ControlDb::inciaCbox("status_usuario", "status");
                                            // Carregando dados da tebela STATUS de Usuario
                                            ?></select>
                                        <script>selectStatus(<?php echo $form['status']; ?>)</script>
                                </label>
                            <?php } else { ?>
                                <input class="input_text" type="hidden" id="h_status" name="status"  value="<?php echo UsuarioControle::CLIENTE ?>"/>
                            <?php } ?>

                            <?php if ($acao) {// valores  hidden para casos de modificações      ?>
                                <input class="input_text" type="hidden" id="h__id" name="id"  value="<?php echo $form['id']; ?>"/>
                                <input class="input_text" type="hidden" id="h_url_img" name="img_perfil"  value="<?php echo $form['img_perfil']; ?>"/>
                            <?php } ?>

                            <label>
                                <output class="msg_erro_input_nome msg_erro_form"></output><br>
                                    <span>Nome: <i>*</i></span><input class="input_text" type="text" id="nome" name="nome"  value="<?php echo $form['nome']; ?>"/></label>
                            <label>
                                <output class="msg_erro_input_sobrenome msg_erro_form"></output><br>
                                    <span>Sobrenome:<i>*</i></span> <input class="input_text" id="sobrenome" name="sobrenome" value="<?php echo $form['sobrenome']; ?>"/></label>
                            <label>
                                <output class="msg_erro_input_dt_nascimento msg_erro_form"></output><br>
                                    <span>Data Nascimento:<i>*</i></span><input class="input_text"  type="date" id="dt_nascimento" name="dt_nascimento" required value="<?php echo $form['dt_nascimento']; ?>"/>
                            </label>
                            <input type="hidden"  name="validar_email" id="validar_email"  value="true"/>

                            <label>
                                <span> Telefone: </span><input type="telefone" class="input_text" id="telefone" name="telefone" placeholder="(00) 000 000" value="<?php echo $form['telefone']; ?>" />
                            </label>

                            <div class="info_localidade_correspondecia">
                                <label>
                                    <output class="msg_erro_input_uf msg_erro_form"></output><br>
                                        <span> UF:<i>*</i> </span>
                                        <select   id="uf" onchange="obterCidades();" name="uf" class="input_text" title="Escolha o estado">
                                            <option class="selec_tipo" >----</option>
                                        </select>

                                </label>
                                <label>
                                    <output class="msg_erro_input_cidade msg_erro_form"></output><br>
                                        <span> Cidade:<i>*</i> </span>
                                        <input type="hidden" class="input_text" name="h_cidade" id="h_cidade"  value="<?php echo $form['cidade']; ?>"/>
                                        <select  id="cidade" onchange="atualizalocalidade(this.value)"  name="cidade" class="input_text" title="Escolha a cidade">
                                            <option class="op_cidade" >----</option>
                                        </select> </label>
                                <label>
                                    <output class="msg_erro_input_endereco msg_erro_form"></output><br>
                                        <span> Endereço: <i>*</i></span><input type="text" class="input_text" id="endereco" name="endereco"  value="<?php echo $form['endereco']; ?>"/>
                                </label>
                            </div><!-- informações para correspondencia-->

                            <div id="form_propriedade_img">
                                <div style="display: none;">
                                    <input   class="input_text"  style="display: none;" type="file" id="img_file" name="img" value="<?php echo $form['img_perfil']; ?>"/>
                                </div>
                                <div id="preview_img">
                                    <label>
                                        <span>Imagem perfil:</span></label>
                                    <div style="width: 200px; float: right;">
                                        <input class="btn_remove" style="visibility: hidden;" id="remove_img" onclick="btn_remove_img(1);" type="button" value="Remover"/><br>
                                    </div>
                                    <label id ="preview_img_user" >
                                        <a onclick="mak_btn_img()"> <img  id ="img_item" src="<?php echo Util::DIR_IMAGEM_USUARIO . $form['img_perfil'] ?>" /><br><i>clique na imagem</i></a>

                                    </label>
                                </div>
                            </div>

                            <div class="op_item">
                                <input id="btn_salvar"  class="lnk_control" type="button" value="Salvar"/>
                                <input   onclick="cancelar('../page/home.phtml');" type="button" class="lnk_control" value="Cancelar" />
                            </div>

                        </div>

                    </form><!--Formulário-->
                    <script src="../script/sha512.js" type="text/javascript"></script>
                    <!--  Script para gerar as opções de Estados e cidades-->
                    <script type="text/javascript">criarOpcaoUF();selectLocalidade(<?php echo $form['uf'] ?>); obterCidades(<?php echo $form['cidade'] ?>);
                    </script>

                    <script type="text/javascript">
                        observeForm('<?php
                        $op = "user";
                        echo $tipo_op . '\',\'' . $op
                        ?>');</script>

                    <?php
                } elseif (isset($_GET['add']) &&
                        $_GET['add'] == 'sucess') { // SE A OPERAÇÃO  FOR FINALIZADA COM SUCESSO EXIBE OS DETALHES DO A DA INSERÇÃO
                    // INCLUE A TELA DE DETALHES
                    require_once 'detalhes_user.php';
                }
                ?>

            </div>
            <?php
            require_once '../util/mascara.php';

            if (isset($erros)) {
                $err = array_keys($erros);
                foreach ($err as $e):
                    ?>
                    <script>msg_box('<?php echo $erros[$e]; ?>')</script>
                    <?php
                endforeach;
                unset($erros);
            }

            if (isset($_SESSION['msg_box'])) {
                ?>
                <script>msg_box('<?php echo $_SESSION['msg_box']; ?>')</script>
    <?php unset($_SESSION['msg_box']);
} ?>

        </div><!-- fima da div conteudo -->

        <div id="rodade_pe">
            <?php
            require_once '../util/rodape.php';
            ?>
        </div><!--rodadé-->
    </body>
</html>